// CREATE TIME OFF REQUEST
export const CREATE_TIME_OFF_REQUEST = 'CREATE_TIME_OFF_REQUEST';
export const CREATE_TIME_OFF_REQUEST_SUCCESS = 'CREATE_TIME_OFF_REQUEST_SUCCESS';
export const CREATE_TIME_OFF_REQUEST_FAILURE = 'CREATE_TIME_OFF_REQUEST_FAILURE';

// GET ALL TIME OFF REQUEST OF CURRENT USER
export const FETCH_TIME_OFF_REQUESTS = 'FETCH_TIME_OFF_REQUESTS';
export const FETCH_TIME_OFF_REQUESTS_SUCCESS = 'FETCH_TIME_OFF_REQUESTS_SUCCESS';
export const FETCH_TIME_OFF_REQUESTS_FAILURE = 'FETCH_TIME_OFF_REQUESTS_FAILURE';

// DELETE TIME OFF REQUEST
export const DELETE_TIME_OFF_REQUEST = 'DELETE_TIME_OFF_REQUEST';
export const DELETE_TIME_OFF_REQUEST_SUCCESS = 'DELETE_TIME_OFF_REQUEST_SUCCESS';
export const DELETE_TIME_OFF_REQUEST_FAILURE = 'DELETE_TIME_OFF_REQUEST_FAILURE';

// UPDATE TIME OFF REQUEST
export const UPDATE_TIME_OFF_REQUEST = 'UPDATE_TIME_OFF_REQUEST';
export const UPDATE_TIME_OFF_REQUEST_SUCCESS = 'UPDATE_TIME_OFF_REQUEST_SUCCESS';
export const UPDATE_TIME_OFF_REQUEST_FAILURE = 'UPDATE_TIME_OFF_REQUEST_FAILURE';